name: sherwood_pub_flutter
description: "A new Flutter project."
publish_to: 'none' # Resta privato

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # Firebase core per inizializzazione
  firebase_core: ^2.23.0

  # Firestore per leggere e scrivere ordini
  cloud_firestore: ^4.9.0

  # Firebase Auth per login sala/cucina
  firebase_auth: ^4.6.3

  # Opzionale: per notifiche push se vorrai aggiungerle
  # firebase_messaging: ^14.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets (esempio, aggiungi immagini/palette se ti servono)
  # assets:
  #   - images/logo.png
  #   - images/icon.png
