// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSEOUJdtGAVzyx5GAwBuZO4jBj_fPvWzM',
    appId: '1:661787603087:web:e447b7e80fe4bdc48f80fa',
    messagingSenderId: '661787603087',
    projectId: 'sherwood-flutter',
    authDomain: 'sherwood-flutter.firebaseapp.com',
    storageBucket: 'sherwood-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMgLCQVukgOKYOVPf_FK8bT2Txt4RmORM',
    appId: '1:661787603087:android:d3b455e081ea66898f80fa',
    messagingSenderId: '661787603087',
    projectId: 'sherwood-flutter',
    storageBucket: 'sherwood-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSEOUJdtGAVzyx5GAwBuZO4jBj_fPvWzM',
    appId: '1:661787603087:web:7343b77c0b7f8c658f80fa',
    messagingSenderId: '661787603087',
    projectId: 'sherwood-flutter',
    authDomain: 'sherwood-flutter.firebaseapp.com',
    storageBucket: 'sherwood-flutter.firebasestorage.app',
  );
}
